wip

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,3 +22,11 @@ jobs:
       run: pip install -r requirements.txt
     - name: Send request
       run: python3 main.py -l 'https://news.ycombinator.com/'
+    - name: Save generated report file
+      uses: actions/upload-artifact@v3
+      with:
+        name: save generated data
+        path: dist/demo-report.tar.gz
+        retention-days: 1
+    - name: Check if the file generate
+      run: [ -s /home/runner/work/web-crawler/web-crawler/output.csv ] && echo "The file genereted successfully || echo "Report could not generated!"
